version: "3.7"
services:
  app:
    command: /bin/bash -c "ni && nr dev"
    build: .
    working_dir: /app
    volumes:
      - .:/app
    tty: true
    environment:
      - NEXT_API_LOCAL_URL=http://app:3000
    ports:
      - 3000:3000
