name: Test
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: install, lint and test, build
        run: |
          npm i -g yarn
          yarn
          yarn lint:eslint
          yarn lint:prettier
          yarn test
          yarn build

  auto-merge:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: build-and-test
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.GITHUB_TOKEN }}
